#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#

if [ -z "$(pgrep pidgin)" ] ; then
    pidgin &
fi

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

if [ -z "$(pgrep synapse)" ] ; then
    synapse -s &
fi

if [ -z "$(pgrep terminator)" ] ; then
    terminator
fi


if [ -z "$(pgrep xautolock)" ] ; then
    xautolock -time 10 -locker "gnome-screensaver-command -l" -notify 10 -notifier "notify-send -t 5000 -i gtk-dialog-info 'Locking in 10 seconds'"&
fi

 export SSH_ASKPASS="/usr/bin/ssh-askpass"
 cat /dev/null | ssh-add &
